### ISSUE TITLE
Question: Relu Kernel Computation

### ISSUE THREAD

**Issue by yCobanoglu** [google/neural-tangents#180]
So the formula for the NTK is:
$$\Theta_{l+1} = \Delta_{l} + (\dot{\Delta_{l}} \odot \Theta_{l}) $$

And in the code this corresponds to 
`ntk *= dot_sigma` in `stax/elementwise.py` in line 442 (for $\dot{\Delta_{l}} \odot \Theta_{l}$)
`ntk = nngp + W_std**2 * ntk` in `stax/linear.py` in line 899 (for $\Theta_{l+1}$)
So the nngp corresponds to $\Delta_{l}$ but why is `dot_sigma` used for  computing the nngp:
`nngp = factor * square_root + dot_sigma * nngp`  in `stax/elementwise.py` line 439 ?

Also i have this reference [Exact Computation NTK](https://arxiv.org/pdf/1904.11955.pdf) (last page) for computing the closed forms for relu.
But if you have any reference or could add the formulas in the docs for computing it would be helpful. Thanks !

**Comment by romanngg** [comment]
Hey, the usage of `dot_sigma` in the ReLU kernel is just coincidental - after massaging the expression in the paper you linked (was first derived here https://papers.nips.cc/paper_files/paper/2009/file/5751ec3e9a4feab575962e78e006250d-Paper.pdf) you can obtain the formula we use in the code, which was just a bit more efficient due to variable reuse / more numerically stable. If needed happy to elaborate on the derivation later!

**Comment by yCobanoglu** [comment]
ok thanks i figured it was a coincidence !

**Comment by yCobanoglu** [comment]
Hey are you sure the relu computation is correct because i saw three paper implementation which all do it differently.
Have you checked the last page of this paper [Exact Computations](https://arxiv.org/pdf/1904.11955.pdf). The formula is efficient and contains no atan2 but arccos ? See their implementation [code](https://github.com/ruosongwang/CNTK/blob/master/CNTK.py). It is just the formula but clamping values so they are in the range of arccos ? Also the paper you linked does not even has the word relu in it. I think you relu activation computation may be incorrect.
