### ISSUE TITLE
eNTK implementation uses deprecated xla attribute

### ISSUE THREAD

**Issue by sim0000** [google/neural-tangents#186]
I was using the eNTK implementation when I ran into this error
`module 'jax.interpreters.xla' has no attribute 'xla_call_p'`
and it seems that xla_call_p has been deprecated after jax 0.4.10. I believe the requirements or implementation need to be updated for this.

**Comment by romanngg** [comment]
Sorry for the late reply - this should've been fixed in https://github.com/google/neural-tangents/commit/49f2c07506149b5792d82c2010d883982b16abae

Please make sure you're installing from head (e.g.
`pip install git+https://www.github.com/google/neural-tangents` (and not from pypi, i.e. not `pip install neural-tangents`), and I will release a new v.0.6.3 soon. Thanks for pointing this out!

**Comment by romanngg** [comment]
Fixed in [v0.6.4](https://github.com/google/neural-tangents/releases/tag/v0.6.4), sorry for the delay!
