### ISSUE TITLE
Problem running the Colab example: error when computing the diagonal of the the NNGP kernel?

### ISSUE THREAD

**Issue by SkanderHn** [google/neural-tangents#19]
When trying to run step 13 in the Colab Cookbook examples (in Colab, not my own Jupyter instance). When trying to compute the the diagonal of the the NNGP kernel: 

```
kernel = kernel_fn(test_xs, test_xs, 'nngp')
std_dev = np.sqrt(np.diag(kernel))

```
I get the following error: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-b771ce84abcc> in <module>()
----> 1 kernel = kernel_fn(test_xs, test_xs, 'nngp')
      2 std_dev = np.sqrt(np.diag(kernel))

9 frames
/usr/local/lib/python3.6/dist-packages/neural_tangents/stax.py in _inputs_to_kernel(x1, x2, marginal, cross, compute_ntk)
    284                      'Use `NO` instead to compute all covariances.')
    285 
--> 286   x1 = x1.astype(xla_bridge.canonicalize_dtype(np.float64))
    287   var1 = _get_variance(x1, marginal_type=marginal)
    288 

AttributeError: module 'jax.lib.xla_bridge' has no attribute 'canonicalize_dtype'

```
Looks like something wrong with the Jax installation, but the pip install:
`!pip install -q git+https://www.github.com/neural-tangents/neural-tangents`
Seemed to run fine.

**Comment by romanngg** [comment]
Are you by any chance running our anonymized code version at https://github.com/neural-tangents/neural-tangents/blob/master/notebooks/neural_tangents_cookbook.ipynb? It's quite old and hasn't been updated since submission, and indeed JAX had breaking changes since. We should update that repo to point here to avoid this.

Please make sure you're running this colab, and let us know if this works!
https://colab.research.google.com/github/google/neural-tangents/blob/master/notebooks/neural_tangents_cookbook.ipynb

**Comment by SkanderHn** [comment]
Thanks - the new Colab notebook works.
