### ISSUE TITLE
Question re: evaluating train and test loss with gradient_descent_mse_gp

### ISSUE THREAD

**Issue by AngusG** [google/neural-tangents#35]
Hi, I need to evaluate both the training and test loss using `predict.gradient_descent_mse_gp`. I'm wondering if there is a more efficient way to do this other than to call `gradient_descent_mse_gp` twice, i.e. with `x_train` and `y_train` fixed while varying the argument to `x_test`. I'm aiming to do this with ~10k data points so each call to this function is rather expensive. Thanks!

**Comment by romanngg** [comment]
Just FYI, this is a great suggestion, and we're planning to address this and several other issues on `predict`, hopefully soon!

**Comment by romanngg** [comment]
Done in a76bbb494f19af4f8c9c1a1b0904e91b105f769e, thanks for the superb suggestion!

Precisely, we now cache the Cholesky / eigendecomposition for different predict calls on different test sets.

Additionally, note that if you don't model any noise on your labels, i.e. `diag_reg=0`, then predictions on the train set are now computed with a simplified formula, and take a bit less time than equivalent computation on the test set. To use this speedup, you should pass `x_test=None` instead of `x_test=x_train`, which you should do if you want to use `diag_reg > 0` on the train set.

Example usage with 15K points:
https://colab.research.google.com/gist/romanngg/6679273701c434f8fbe5127dc031751a/predict_train_and_test.ipynb
