### ISSUE TITLE
Channel Dimension for `mat` in `_conv_kernel_diagonal_spatial`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#50]
Hi, can we tell which dimension is the channel dimension for the input matrix `mat` and for the parameter `filter_shape`? Or can I assume there is only one channel by default? Thanks a lot!

[https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3058](https://github.com/google/neural-tangents/blob/master/neural_tangents/stax.py#L3058)

**Comment by romanngg** [comment]
There are actually no channel dimensions in `mat` there (and in other places like this, where you work with covariance matrices) - e.g. if your finite-width inputs are `NCHW`, then `mat` is `N1N2HW`, and the convention is that covariance between `x[n1, c1, h, w]` and `x[n2, c2, h, w]` is `mat[n1, n2, h, w]` if `c1 == c2` and `0` otherwise, for any (out of infinity) channels `c1` and `c2`.

Respectively, the operation performed, `lax._reduce_window_sum`, is agnostic to how axes are labeled (batch, channel, etc), and is fully specified by filter shape and strides - note that `len(filter_shape) == len(strides) == mat.ndim` in that example.

Lmk if this helps!

**Comment by DarrenZhang01** [comment]
I see. I asked this question because there is minor difference between the input requirement of JAX `_reduce_window_sum` and TF `pool`. Generally speaking, for TF `pool`, it requires `mat.ndim == len(filter_shape) + 2`, where the `2` represents batch dimension and channel dimension separately. Obviously in Neural Tangents, the batch dimensions are the leading dimensions, so I can manually remove them for the filter shape. For the channel dimension, since my realization of TF version of `reduce_window` depends on TF `pool`, I guess what I should do is manually append a channel dimension `1` to the end of `mat` in order to satisfy the above dimensionality constraint.

Thanks very much, Roman! @romanngg

**Comment by DarrenZhang01** [comment]
Hi Roman @romanngg , I have a followup question: when there are more than one leading dimensions, is it reasonable to combine them into one? For example, `mat[n1, n2, h, w] => mat[n, h, w]`. (Again, TF `pool` only allows one batch dimension) Thanks!

**Comment by romanngg** [comment]
Yes, that's a good idea!
