### ISSUE TITLE
batch version of gradient_descent_mse_gp function

### ISSUE THREAD

**Issue by ravidziv** [google/neural-tangents#8]
I'm getting 'out of memory' error when I use 'gradient_descent_mse_gp' function caused by the np.einsum in the 'prediction' function.
Is there a way to make a batch version of this function?

**Comment by romanngg** [comment]
Unfortunately we don't have it implemented right now. To batch I can only suggest removing the `x_test` argument from `gradient_descent_mse_gp` and adding a pair of `x_test_1, x_test_2` arguments to the `prediction` function, recomputing `ktt`, `ktd` and `kdt` inside `prediction` with each call instead of precomputing it in `gradient_descent_mse_gp`. That way you should be able to loop over pairs of test inputs outside. I guess the memory gain here would be not having to instantiate `ktd`, but since you need to store `kdd` and `ktt` anyway, it might not be that much IMO.

One other way to gain memory is to run these computations on CPU even while executing `kernel_fn` on a GPU - this is something I hope we'll have pretty soon!

Another option is trying to call `prediction` with/without `jit` and see if it changes the memory footprint. 

Not sure if einsum could be causing the issue, but you could also check if using manual matmul ops like below helps.
```
@jit
def eins_mm(ktd, evecs, op_evals):
  op_evals = np.expand_dims(op_evals, 1)
  res = np.dot(evecs, op_evals * evecs.T)
  res = np.dot(np.dot(ktd, res), ktd.T)
  return res
```

**Comment by romanngg** [comment]
5bb50ba30c463b8c8b5a06aa0e2e46181779c6fa should make it possible to do inference with `gradient_descent_mse_gp` and `gp_inference` on CPU, if you pass them a kernel function that collects kernel matrices on CPU, e.g. `kernel_fn = nt.batch(kernel_fn, ..., store_on_device=False)`, let me know if this helps in your use-case!

**Comment by ravidziv** [comment]
@romanngg  it helps to run computations on CPU.
Thanks!
